# Question on Numpy Array

write answer of each question and also give explanation with example.

In [62]:
# 1 how to create an empty and a full numpy array.
#Ans :An empty NumPy array can be created using the numpy.empty() function.
#        A full NumPy array can be created using the numpy.full() function.

# example of empty 

import numpy as np
empty_array = np.empty((3, 3))
print("Empty NumPy array:")
print(empty_array)

full_array = np.full((2, 2), 5)

print("Full NumPy array:")
print(full_array)

Empty NumPy array:
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
Full NumPy array:
[[5 5]
 [5 5]]


In [35]:
# 2 create a numpy array filled with all zeros.
# ans : To create a NumPy array filled with all zeros, you can use the numpy.zeros() function.

import numpy as np

zero_array = np.zeros([2,3])

zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 3 create a numpy array filled with all ones
# ans : To create a NumPy array filled with all ones, you can use the numpy.ones() function.

import numpy as np
ones_array = np.ones([4,3])
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# 4 check whether a numpy array contains a specified row. 
# This can be done by using simple approach as checking for each row with the given list but this can be easily understood and 
# implemented by using inbuilt library functions numpy.array.tolist().If the given list is present in a array as a row then 
# the output is True else False.

arr = np.array([[6,7,8,9,10], 
                [16, 17, 20, 19, 180], 
                [1, 2, 3, 4, 5], 
                [11, 12, 13, 14, 15]]) 
 
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 

True
False
False
True


In [105]:
# 5 how to remove rows in numpy array that contains non-numeric values.
# ans : you can use boolean indexing along with the numpy.isnan() function

import numpy as np


arr = np.array([[1, np.nan, 3],
                [4, 7, 6],
                [np.nan, 8, 9]])


arr_numeric = arr[~np.isnan(arr).any(axis=1)]

arr_numeric

array([[4., 7., 6.]])

In [50]:
# 6 remove single-dimensional entries form the shape of an array
# ans : numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.
input_arr = np.array([[[2, 2, 2], [2, 2, 2]]]) 
   
print ("Input array : ", input_arr)  
print("Shape of input array : ", input_arr.shape)   
  
output_arr = np.squeeze(input_arr)  
  
print ("output squeezed array : ", output_arr) 
print("Shape of output array : ", output_arr.shape)

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [49]:
# 7 find the number of occurrences of a sequence in numpy array
# ans : To find the number of occurrences of a sequence in a NumPy array, you can use the numpy.where() function
import numpy as np

arr = np.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 
output = repr(arr).count("9, 4") 
print(output) 

4


In [53]:
# 8 find the most frequent value in a numpy array
# ans : To find the most frequent value in a NumPy array, you can use the numpy.unique() function to get the unique elements and their counts, and then use numpy.argmax() to find the index of the maximum count.

import numpy as np

a = np.array([22,22,33,44,5,11,22,22,11,11]) 
  
print("Most frequent value in the above array:",np.bincount(a).argmax()) 

Most frequent value in the above array: 22


In [55]:
# 9 combining a one and a two -dimensional numpy array
# ans : NumPy array, you can use NumPy's stacking functions like np.vstack() 

import numpy as np

num_1d = np.arange(5) 
  
num_2d = np.arange(10).reshape(2,5) 

for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [58]:
# Q.10 How to build an array of all combinations of two NumPy arrays?
# Numpy has a function to compute the combination of 2 or more Numpy arrays named as “numpy.meshgrid()“. This function is used 
# to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.

import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])

comb_array = np.array(np.meshgrid(array1, array2)).T.reshape(-1, 2) 
  
comb_array

array([[1, 4],
       [1, 5],
       [2, 4],
       [2, 5],
       [3, 4],
       [3, 5]])

# function 1 zero()

In [64]:
# Example 1 
# Explanation: This will create a 2D array with 3 rows and 2 columns filled with zeros, stored in Fortran (column-major) order instead of the default C (row-major) order.

import numpy as np
arr = np.zeros((3, 2), order='F')
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [66]:
# Example 2 
#Explanation: This will create a 1D array filled with integer zeros instead of the default floating-point zeros.

arr = np.zeros(5, dtype=int)
print(arr)

[0 0 0 0 0]


In [67]:
# Example 3 
# Explanation: This will create a 3D array with dimensions 2x3x4, all filled with zeros. It has 2 matrices, each with 3 rows and 4 columns, resulting in a shape of (2, 3, 4).


arr = np.zeros((2, 3, 4))
print(arr)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# function 2 arange()

In [20]:
# Example 1 
# Explanation : This will create an array [0, 1, 2, 3, 4]. The arange() function generates values starting from 0 up to (but not including) the specified stop value, with a default step of 1.
import numpy as np 

arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [21]:
# Example 2 
# This will create an array [1, 3, 5, 7, 9]. The arange() function allows specifying the start, stop, and step values. In this example, it generates values starting from 1 up to (but not including) 10, with a step of 2.

arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [68]:
# Example 3 
# Explanation This will produce an array [0. 0.25 0.5 0.75 1. ], ensuring precise control over the number of elements and avoiding potential floating-point arithmetic errors.

arr = np.arange(0,1,0.25)
arr

array([0.  , 0.25, 0.5 , 0.75])

 # function 3 reshape()

In [28]:
# Example 1 
# Explanation : This will reshape the 1D array [1, 2, 3, 4, 5, 6] into a 2D array with 2 rows, with the number of columns automatically calculated to be 3.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, -1))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Exampele 2
# Explanation: This will reshape the 1D array [1, 2, 3, 4, 5, 6, 7, 8] into a 2D array with 4 rows. The -1 in the shape tuple allows NumPy to automatically calculate the number of columns needed to maintain the total number of elements.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reshaped_arr = np.reshape(arr, (4, -1))
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
# Exampele 3 
# Explanation: This will reshape the 2D array [[1, 2, 3], [4, 5, 6]] into a 1D array [1, 2, 3, 4, 5, 6].

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.reshape(arr, 6)
arr

array([1, 2, 3, 4, 5, 6])

# function 4 std()

In [37]:
# Example 1
# Explanation: This will calculate the standard deviation of the 1D array [1, 2, 3, 4, 5]. The standard deviation is a measure of the amount of variation or dispersion of a set of values. In this example, it computes the standard deviation of the elements in the array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

std = np.std(arr)

print(std)

1.4142135623730951


In [45]:
# Example 2 
# Explanation: This will calculate the standard deviation along the columns (axis=0) of the 2D array [[1, 2, 3], [4, 5, 6]]. It computes the standard deviation for each column separately and returns an array containing the standard deviation values for each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

std = np.std(arr, axis=0)

print(std)

[1.5 1.5 1.5]


In [48]:
# Exampale 3 
# Explanation: This will compute the sample standard deviation along the rows (axis=1) of the 2D array [[1, 2], [3, 4], [5, 6]] with degrees of freedom (ddof) set to 1. It computes the standard deviation for each row separately, considering each row as a sample.

arr = np.array([[1, 2], [3, 4], [5, 6]])

std = np.std(arr, axis=1, ddof=1)
print(std)


[0.70710678 0.70710678 0.70710678]


# function 5 linspace()

In [41]:
# Example 1 
# in the generated array. However, setting endpoint=False excludes the endpoint from the generated array. In this example, we generate 10 equally spaced numbers between 0 and 2, excluding the endpoint.

import numpy as np

arr = np.linspace(0, 2, 10, endpoint=False)
print(arr)


[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [43]:
# Example 2
# Explanation: By default, numpy.linspace() returns an array of floating-point numbers. However, we can specify the data type of the array using the dtype parameter. In this example, we generate an array of 6 equally spaced integers between 1 and 10.

arr = np.linspace(1, 10, 6, dtype=int)
print(arr)

[ 1  2  4  6  8 10]


In [44]:
# Example 3 
# Explanation: This example generates an array containing 20 equally spaced numbers between 0 and 10. Instead of specifying the step size, we provide the num parameter to indicate the number of points we want in the range.

arr = np.linspace(0, 10, num=20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
